### ISSUE TITLE
Implicit Authorization Flow Implementation

### ISSUE THREAD

**Issue by Aakash2211** [gsuitedevs/apps-script-oauth2#113]
I want to implement Oauth2 Implicit Authorization Flow with Gmail Add-Ons. I have used Apps Script's new StateTokenBuilder and /usercallback endpoint to handle the redirects. For the same, I have created the Authorization url on which user is redirected in another tab when he/she opted for authentication. After successful validation, there is the redirection to the below url.

https://script.google.com/macros/d/SCRIPT_ID/usercallback#access_token=ACCESS_TOKEN&token_type=TOKEN_TYPE&expires_in=86399992

But Unfortunately the redirection will not happen as per expectation. But in redirection url if we use ? (.. /usercallback?access_token ..) instead of # (.. /usercallback#access_token ..) , the redirection works. Can you please explain where I am doing wrong.

**Comment by erickoledadevrel** [comment]
Closing this issue, as it doesn't appear to be related to this library.

The state token must be passed as a URL parameter (using the "?"), as Apps Script needs that to read that to prevent against certain kinds of attacks.
