### ISSUE TITLE
URL whitelist error

### ISSUE THREAD

**Issue by deepika537** [gsuitedevs/apps-script-oauth2#114]
Trying to open a website on button click. It gives me an error as below eventhough I have whitlisted the url in manifest file. Please let me know How can I fix this issue.
URL (https://login.salesforce.com/) does not match any of the prefixes whitelisted for use in the add-on.
Whitelist:
Original:
- https://mail.google.com/
Effective:
- https://mail.google.com/

**Comment by erickoledadevrel** [comment]
This issue tracker is for the OAuth library, and this seems to be a problem with Gmail add-ons:

https://developers.google.com/gmail/add-ons/concepts/manifests#whitelisting_urls

That said, I tested it out and I'm able to successfully whitelist URLs used in the OAuth flow. If you aren't using a HEAD deployment you'll need to deploy a new version of your script for the whitelist change to take effect.

**Comment by deepika537** [comment]
I tested with HEAD deployment and a new version It did not work. It does not give any error with google website urls

var buttonSet = CardService.newButtonSet();
    var button = CardService.newTextButton()
     .setText("This button opens a link in an overlay window")
     .setOpenLink(CardService.newOpenLink()
         .setUrl('https://login.salesforce.com/')
         .setOpenAs(CardService.OpenAs.FULL_SIZE)//setOpenAs(CardService.OpenAs.FULL_SIZE)
         .setOnClose(CardService.OnClose.RELOAD_ADD_ON));
    buttonSet.addButton(button);

**code in manifest file**
  "urlFetchWhitelist": [
   "https://login.salesforce.com/", "https://fm1--sandbox01.cs47.my.salesforce.com/",
    "https://en.wikipedia.org/wiki/"
  ],
 "openLinkUrlPrefixes": [
"https://login.salesforce.com/",
      "https://mail.google.com/",
      "https://script.google.com/a/google.com/d/",
      "https://drive.google.com/a/google.com/file/d/",
      "https://en.wikipedia.org/wiki/",
      "https://www.example.com/"
    ],

**Comment by jsierens** [comment]
Made te same mistake. It should be like **gmail**.openLinkUrlPrefixes

  "gmail": {
...
    "openLinkUrlPrefixes": [
      "https://login.salesforce.com/",
      "https://mail.google.com/",
      "https://script.google.com/a/google.com/d/",
       "https://drive.google.com/a/google.com/file/d/",
       "https://en.wikipedia.org/wiki/",
       "https://www.example.com/"
    ]
  }
