### ISSUE TITLE
Error-Session expired or Invalid

### ISSUE THREAD

**Issue by deepika537** [gsuitedevs/apps-script-oauth2#115]
I am trying to access the SalesforceAPI from Google App script and I have used OAuth protocol for authorization. I was able to pull the salesforce information in the application successfully for the first time. However, on the next day I got the following error.
[   {     "message": "Session expired or invalid",     "errorCode": "INVALID_SESSION_ID"   } ]
When I got the error first time. I have created new appscript and copy pasted the code from previous app script as it is and it worked for one day without any error again next day onwards I am getting the same error.
If there were any problem with access token or instance url then it would not work in the first place itself. I think problem is not with instance url or access token.

How can I fix this issue?

////Request
function getService() {
  return OAuth2.createService('Saleforce')
      // Set the endpoint URLs.
      .setAuthorizationBaseUrl('https://login.salesforce.com/services/oauth2/authorize')
      .setTokenUrl('https://login.salesforce.com/services/oauth2/token')

      // Set the client ID and secret.
      .setClientId(CLIENT_ID)
      .setClientSecret(CLIENT_SECRET)

      // Set the name of the callback function that should be invoked to
      // complete the OAuth flow.
      .setCallbackFunction('authCallback')
      // Sets the login hint, which will prevent the account chooser screen
      // from being shown to users logged in with multiple accounts.
      .setParam('login_hint', Session.getActiveUser().getEmail())
      
      // Requests offline access.
      .setParam('access_type', 'offline')

      // Forces the approval prompt every time. This is useful for testing,
      // but not desirable in a production application.
      .setParam('approval_prompt', 'force')
    

      // Set the property store where authorized tokens should be persisted.
      .setPropertyStore(PropertiesService.getUserProperties());
}

//response
var url1 = service.getToken().instance_url +parameter1;
    var headers={
        Authorization: 'Bearer ' + service.getAccessToken()
      };
    var options = {muteHttpExceptions: true,"headers":headers};
    var response1 = UrlFetchApp.fetch(url1,options);
    Logger.log(response1);

Output:
[{"message":"Session expired or invalid","errorCode":"INVALID_SESSION_ID"}]

**Comment by erickoledadevrel** [comment]
The existing Salesforce sample wasn't requesting a refresh token, and the Salesforce OAuth implementation expires tokens dynamically requiring a different flow for refreshing them. I've updated the Salesforce sample in #116.
