### ISSUE TITLE
State Token Too Long

### ISSUE THREAD

**Issue by ZanGOlie** [gsuitedevs/apps-script-oauth2#117]
I am thus far unable to integrate with the UltraCart API as I'm getting an error with description;
"The state parameter cannot exceed 250 characters."

Is there a way to make State Tokens shorter and ensure they do not cross the 250 limit?

**Comment by erickoledadevrel** [comment]
I tried to replicate the problem, but didn't get an error about the state parameter length. I've published my code as a sample:

https://github.com/gsuitedevs/apps-script-oauth2/blob/master/samples/UltraCart.gs

Are you using a different UltraCart API? (It looks like they have a few).

**Comment by ZanGOlie** [comment]
Thanks for the response @erickoledadevrel 

After seeing your code (which is basically the same as mine) I realised the problem is not where I thought. The background is that I'm creating a Google Data Studio connector, and even though it uses this OAuth2 library, it seems that it is using a longer State Token than what the library would generate.

Turns out my code works just fine if I do it directly as in your sample (I did a similar 'run' function in the same project), but fails in Data Studio. Data Studio seems to be creating state tokens in excess of 300 characters!

**Comment by erickoledadevrel** [comment]
Is Data Studio generating a completely different redirect URI, or is it still the `/usercallback` URI but with a longer state token?

**Comment by ZanGOlie** [comment]
The authorization URIs generated have the same parameters, including the redirect uri, except that Data Studio has a longer state token

**Comment by erickoledadevrel** [comment]
I'm not sure what Data Studio is doing, but it sounds like the problem lies there and not in this library. Closing for now.
