### ISSUE TITLE
Broken page

### ISSUE THREAD

**Issue by enderahmetyurt** [gsuitedevs/apps-script-oauth2#120]
This page is broken. https://googlesamples.github.io/apps-script-oauth2/Service_.html Why? Could you help?

**Comment by erickoledadevrel** [comment]
Sorry, the link in the README was outdated. It's been updated to the correct link:

http://gsuitedevs.github.io/apps-script-oauth2/Service_.html

**Comment by enderahmetyurt** [comment]
Cheers.
