### ISSUE TITLE
Auth0 compatibility (query not hash)

### ISSUE THREAD

**Issue by queenvictoria** [gsuitedevs/apps-script-oauth2#121]
Thank you for the great work on this library!

I'm using Auth0 for the OAuth2 authorisation of a Google Sheets script.
My issue seems to be similar to #45 for Dropbox. 

I set the `redirect_uri` parameter for Auth0 thusly:

```
    .setParam('redirect_uri', 'https://script.google.com/macros/d/' + scriptID + '/usercallback')
```

The script correctly generates an URL that includes my `redirect_uri` 
Auth0 picks up the request, generates a token, and redirects me to the scripts.google.com domain.
Once hitting scripts.google.com I am redirected to an URL that includes my custom domain.

https://script.google.com/a/macros/[custom-domain]/d/[script-id]/usercallback#access_token=[token]&expires_in=7200&token_type=Bearer&state=[state]&id_token=[token]

Which results in an error page:

### Sorry, unable to open the file at present.
> Please check the address and try again.

If I change the URL back (without the custom domain) it redirects again.

As an added complexity, I am logged in to two GSuite domains and the redirect picks the primary one rather than the one I'm working in. If I change the URL to the correct domain, or use an incognito window, I get the same result.

I can change the `response_mode` to query (so we can get a redirect URL with a `?` rather than a `#`), which means I have to change the `response_type` to `code` instead of `token`. 

```
    .setParam('response_type', 'code')
    .setParam('response_mode', 'query')
```

This results in a redirection without a token and a response from the Google app script as follows: 

```
The state token is invalid or has expired. Please try again.
```

The requirement to change the `response_mode` to `code` is outline here as a requirement of the spec:
https://github.com/auth0/auth0.js/issues/479#issuecomment-338720730

Does anyone have any recommendations as how best to proceed?

Note: If I manually alter the resulting URL that contains the hash to a query instead I still get the invalid/expired error.

**Comment by TimJohns** [comment]
I wonder if this is relevant: https://github.com/google/google-auth-library-nodejs/pull/349

By quick inspection (with potentially faulty memory on the topic!), it looks like maybe `Service_.prototype.getAuthorizationUrl()` takes into account the this.params_[redirect_uri] but perhaps `Service_.prototype.handleCallback` does not.

If I get a chance I will dig in further, but leaving this here in hopes maybe someone more familiar with the Apps Script lib gets an 'ah-ha!' moment from it.

**Comment by queenvictoria** [comment]
@erickoledadevrel you are correct. If I remove redirect_uri and keep `request_type` and `request_mode` as above then I get the success message. I'll close this ticket. Thank you for your help!

For reference here is a complete Auth0 service. I'll update it when I have completed the end-to-end tests.

```javascript
// Authentication with Auth0 using https://github.com/gsuitedevs/apps-script-oauth2 (included via Resources > Libraries)
function getAuthService() {
  return OAuth2.createService('Auth0')

    // Set the endpoint URLs.
    .setAuthorizationBaseUrl('https://[DOMAIN].auth0.com/authorize')
    .setTokenUrl('https://[DOMAIN].auth0.com/oauth/token')

    // Set the client ID and secret, from the Auth0 application settings.
    .setClientId('[CLIENTID]')
    .setClientSecret('[CLIENTSECRET]')

    // Set the name of the callback function in the script referenced
    // above that should be invoked to complete the OAuth flow.
    .setCallbackFunction('authCallback')

    // Set the property store where authorized tokens should be persisted.
    .setPropertyStore(PropertiesService.getUserProperties())

    // Set the scopes to request (space-separated for Auth0 services).
    .setScope('openid profile email')

    // Below are Auth0-specific OAuth2 parameters.
    .setParam('audience', 'https://[AUTH0AUDIENCE]')
    .setParam('response_type', 'code')
    .setParam('response_mode', 'query')
  ;
}

// showSidebar and authCallback as per readme. Will update shortly if needed.
```

**Comment by queenvictoria** [comment]
Ok so that looks like all. At this stage I didn't need anything further. Perhaps, in future, caching. Thanks all.

**Comment by ForzaZzh** [comment]
Hello @queenvictoria 
I have similar issue with Auth0. I did the same but I it seems that I get the authorization_code and not the access_token.
After successfull login I'm redirected to the uri - https://script.google.com/macros/d/[SCRIPT_ID]/usercallback?code=[AUTH_CODE]&state=[STATE]

I took the AUTH_CODE here and tried it in postman following [auth0 docs](https://auth0.com/docs/api/authentication#authorization-code) 

` {
  "grant_type": "authorization_code",
  "client_id": "[CLIENTID]",
  "client_secret": "[CLIENTSECRET]",
  "code": "[AUTH_CODE ]",
  "redirect_uri": "https://script.google.com/macros/d/[SCRIPT_ID]/callback"
} `

the response is 

`{
    "error": "invalid_grant",
    "error_description": "Invalid authorization code"
}`

Also, I do not quite understand where and how the authorization code will be exchange for access token?
Any help will be appreciated! Thanks!

**Comment by erickoledadevrel** [comment]
@ForzaZzh - When using this library you just need to feed the request object into the service's `handleCallback()` method, as [shown in the README](https://github.com/gsuitedevs/apps-script-oauth2#3-handle-the-callback).

**Comment by ForzaZzh** [comment]
@erickoledadevrel - Yes, this is exactly what I did and still I cannot get the token

**Comment by erickoledadevrel** [comment]
Is it throwing an error?

**Comment by ForzaZzh** [comment]
Hi, It's not throwing any errors but I found my stupid mistake - I didn't get the token from the authService
`driveService.getAccessToken()`
Thanks!

**Comment by erickoledadevrel** [comment]
The folks in that thread are referring to unofficial, open-source command
line tool for G Suite administration called GAM:

https://github.com/jay0lee/GAM

Not to be confused with the Google Apps Marketplace (GAM), now called the G
Suite Marketplace (GSM).

As for thanking Ross, we could send out a tweet from the @gsuitedevs
Twitter handle, or publish a blog post on the G Suite Developers blog. @Joanna
Smith <joannasmith@google.com> - do you think the content team would be up
for that? @Charles Maxson <cmaxson@google.com> - Would it be worth
investigating if Ross could join the Google Developer Experts (GDE) program?

- Eric

**Comment by erickoledadevrel** [comment]
Please ignore my last comment in this thread, it was posted here by accident.
