### ISSUE TITLE
Attribute provided with invalid value: Header:toType (line 361, file "Service", project "OAuth2")

### ISSUE THREAD

**Issue by Rohed** [gsuitedevs/apps-script-oauth2#123]
After clicking the redirect link and logging into my account i get: 
Attribute provided with invalid value: Header:toType (line 361, file "Service", project "OAuth2")

Older versions of the script seem to show the same error except on line 303. Nothing has changed from the previous working script aside from testing as an add - on.

**Comment by erickoledadevrel** [comment]
Which API are you connecting to? Can you provide some sample code?

**Comment by Rohed** [comment]
`function getBQService_() {
  var GOOGLE_SECRET_AND_CLIENTID=getGoogleSAC();
  return OAuth2.createService('BigQuery')
  .setAuthorizationBaseUrl('https://accounts.google.com/o/oauth2/auth')
  .setTokenUrl('https://accounts.google.com/o/oauth2/token')
  .setClientId(GOOGLE_SECRET_AND_CLIENTID[0])
  .setClientSecret(GOOGLE_SECRET_AND_CLIENTID[1])
  .setCallbackFunction('authCallbackBQ')
  .setPropertyStore(PropertiesService.getUserProperties())
  .setScope(['https://www.googleapis.com/auth/bigquery',
             'https://www.googleapis.com/auth/devstorage.full_control',
             'https://www.googleapis.com/auth/devstorage.read_write',
             'https://www.googleapis.com/auth/cloud-platform',
             'https://www.googleapis.com/auth/analytics'])
  .setParam('access_type', 'offline');;
  
}`

Note getGoogleSAC(), just return the client ID and Secret from a variable.

`function authCallbackBQ(request) {
  var service = getBQService_();
  var authorized = service.handleCallback(request);
  if (authorized) {
    return HtmlService.createHtmlOutput('Success!');
  } else {
    return HtmlService.createHtmlOutput('Denied.');
  }

}`

Reducing/Increasing the number of scopes doesn't seem to do anything to affect the issue.

**Comment by erickoledadevrel** [comment]
Looking at the Apps Script code, this error seems to indicate that `UrlFetchApp.fetch()` had trouble with the payload of the request. This library provides a `setTokenPayloadHandler()` method that allows developers to augment the payload before it is sent. Are you using this feature by any chance?

**Comment by Rohed** [comment]
Turns out urlfetchapp was pulling the prototype functuons along with the object. In my case toType was an Object.prototype function and uppon checking with getRequest() the entire function was pullled along with the object header.

**Comment by erickoledadevrel** [comment]
@Rohed - Was that because you added extra code to the prototype? I don't think `getRequest()` is called anywhere in this library.

**Comment by Rohed** [comment]
Yes, when sending the params in UrlFetchApp.fetch(url, params), every object in the params had this external function i had made pulled along with it. So the issue was on my side. But because i used the library for oauth the errors were showing in the librarys code instead of mine

**Comment by erickoledadevrel** [comment]
I see. In general it isn't a good idea to extend the prototype of Apps Script services, as it can lead to unexpected consequences. Glad you figured it out!

**Comment by postman31** [comment]
An error is raised when there exists a property of `options.headres` in `UrlFetchApp.fetch(url, options)` of undefined value. reproducible with the following code:
`
function tt() {
  var url  = 'https://google.com'
  var options1 = { headers: { 'some_header' : 'ok' }}
  var options2 = { headers: { 'some_header' :  undefined } }
  var optionList = [options1, options2]
  optionList.map(function (options) {
    try {
      var response = UrlFetchApp.fetch(url, options)
      Logger.log('responded with %s', response.getResponseCode())
    } catch (e) {
      Logger.log('Got error %s', e)
    }
  })
}
`
