### ISSUE TITLE
Google Apps Script: You do not have permission to call fetch

### ISSUE THREAD

**Issue by glaand** [gsuitedevs/apps-script-oauth2#125]
Greetings
I'm having this problem with a google account from my company.
I've run the script on the Script Editor, gave the right permissions
```
"oauthScopes": [
    "https://www.googleapis.com/auth/script.external_request",
    "https://www.googleapis.com/auth/spreadsheets"
  ]
```
And it is working there!
The strange part is that it isn't working if the `onEdit`function is triggered by a spreadsheet.

What am i missing?

**Comment by erickoledadevrel** [comment]
The `onOpen` simple trigger can't use services that require scopes, and `UrlFetchApp` requires the `script.external_request` scope. You can use an installed trigger instead.

**Comment by andrereislive** [comment]
> `UrlFetchApp`
@erickoledadevrel 
Is it possible to do a UrlFetchApp inside the onOpen(e) of a SlidesApp ?

**Comment by tinoargentino** [comment]
@erickoledadevrel great thanks for clarifying that!
