### ISSUE TITLE
Ring Central REST "Redirect URIs do not match"

### ISSUE THREAD

**Issue by Nathaniel-MacIver** [gsuitedevs/apps-script-oauth2#129]
I was hoping to use your OAuth2 Library to pull Ring Central call data for recording in my instance of Google BigQuery via Google Apps Script. To start, I added the library and used doGet to render a simple page to generate a token that I can start making calls with. On clicking Authorize, I get the following HTTPS response:

`{
  "error" : "invalid_grant",
  "error_description" : "Redirect URIs do not match",
  "errors" : [ {
    "errorCode" : "OAU-109",
    "message" : "Redirect URIs do not match"
  } ]
}`

For Reference, My result from logCallback is this: 
`https://script.google.com/macros/d/[MY SCRIPT ID]/usercallback`

Attached are my .gs files to get me this far.
[OAuthTest.txt](https://github.com/gsuitedevs/apps-script-oauth2/files/2199243/OAuthTest.txt)
[OAuthLibrary.txt](https://github.com/gsuitedevs/apps-script-oauth2/files/2199244/OAuthLibrary.txt)

Could you help me make this work? I'm sure you can tell I have practically no experience handling OAuth requests.

   Thanks!

**Comment by erickoledadevrel** [comment]
I've posed a sample for the RingCentral API, which I hope should help:

https://github.com/gsuitedevs/apps-script-oauth2/blob/master/samples/RingCentral.gs

This error usually indicates that you've registered the wrong redirect URI in the developer console. Double check that the value of "OAuth Redirect URI" in the RingCentral developer console matches the value that `logRedirectUri()` returns.

**Comment by Nathaniel-MacIver** [comment]
Thanks for Getting Back to me. Running the script did get me to an authorization prompt I hadn't reached before (image 1), and I logged in with my project credentials and my actual Ring Central User account, but was redirected both times to the following URL: https://script.google.com/a/macros/coordinationcentric.com/d/[My Project ID]/usercallback?error=invalid_request&error_description=OAU-144:Only+bot+extension+can+be+used+with+given+app+type

I can confirm that my project is currently set to expect OAuth Redirect URI https://script.google.com/macros/d/[MY PROJECT ID]/usercallback (image 2), which is what GAS is configured to put out (image 3).

Anything else I can try?





![screenshot 1](https://user-images.githubusercontent.com/26629632/42841701-e5eb71de-89d8-11e8-8cc2-7bdd3f09c386.png)
![screenshot2](https://user-images.githubusercontent.com/26629632/42841535-634691d2-89d8-11e8-9155-ae465d68d7a9.png)
![screenshot 3](https://user-images.githubusercontent.com/26629632/42841644-b4b6544e-89d8-11e8-8d5d-9d4bf4a90d39.png)

**Comment by erickoledadevrel** [comment]
It looks like you selected Server/Bot for the platform type in the
RingCentral console, instead of Server/Web which is what you need.

**Comment by Nathaniel-MacIver** [comment]
Got it. I recreated the app under "Web Browser," and now it accepts calls from my Apps Script Environment. You rock, Eric!
