### ISSUE TITLE
Getting "OAuth2 is not defined" error

### ISSUE THREAD

**Issue by StephanieDeguire** [gsuitedevs/apps-script-oauth2#130]
![oauth2](https://user-images.githubusercontent.com/41380033/42887004-f572c3f6-8a72-11e8-9571-6ff997229638.png)

I'm trying to use the script in appmaker. I followed the setup procedure but I still get the same error.

**Comment by erickoledadevrel** [comment]
I just did the same configuration, and it worked without error. Can you show me the code where you try to use it? Are you sure you're calling it from a server-side script and not a client-side one?

**Comment by StephanieDeguire** [comment]
Oh!!! So sorry!!  

My script was on a client-side!
