### ISSUE TITLE
Add an option to pass a custom parameter to the callback function

### ISSUE THREAD

**Issue by tdelmas** [gsuitedevs/apps-script-oauth2#131]
Example of API:
```
.setCallbackFunction('authCallback')
.setCallbackParameter('mycustomvalue')
```

Result:
```
function authCallback(request) {
  // here, request.parameter = 'mycustomvalue'
}
```
So the template rendered in authCallback could have custom information.

It could be done for example using https://github.com/gsuitedevs/apps-script-oauth2/blob/master/src/Service.js#L308
```
  var state = eval('Script' + 'App').newStateToken()
      ...
      .withArgument('serviceName', this.serviceName_)
      .withArgument('parameter', this.customValue_)
      ...
      .createToken();
```

**Comment by erickoledadevrel** [comment]
Ya, sounds very doable. What kind of information would you want to pass?

**Comment by tdelmas** [comment]
Thanks! Right now, I want to pass the lang, to have the same on than on the Authorization Card (get from event.userLocale)
(But If I need to pass more data, I'll probably use JSON.stringify)

My workaround is to use the cache to set the lang when I build the Authorization Card, and then read it in authCallback.
It works, mostly for the lang, but to pass more structured data, and ensure they came from a specific workflow, that workaround doesn't help.

(About the lang, I've open another issue there: https://issuetracker.google.com/issues/111662662)

**Comment by tdelmas** [comment]
Thanks !
