### ISSUE TITLE
Closing the OAuth window show the previous card from cache

### ISSUE THREAD

**Issue by tdelmas** [gsuitedevs/apps-script-oauth2#132]
(I know that issue is not on your end, but your documentation is I thing the right place to document the workaround)

https://issuetracker.google.com/issues/111707633
TL;RD: If using AuthorizationException, When the user is connected, clicks on logout, click on the button to open the OAuth2 popup and close it (without validating it) the addon will shows from cache the cards where he was with the logout button.

The workaround I have is to manually shows the Authorization Card using a Navigation **with .setStateChanged(true)** : When the user close the OAuth2 popup and close it (without validating it) the addon calls onTriggerFunction's callback and show the up-to-date home (so, not connected)

**Comment by erickoledadevrel** [comment]
I think the best place to document this would be in the Authorization guide in the Gmail Add-ons documentation:

https://developers.google.com/gmail/add-ons/how-tos/authorizing

I'll follow up with you on the issue tracker.
