### ISSUE TITLE
Can not add library to a Google Data Studio connector

### ISSUE THREAD

**Issue by duracelltomi** [gsuitedevs/apps-script-oauth2#140]
I followed the setup instructions but after entering the script ID `1B7FSrk5Zi6L1rSxxTDgDEUsPzlukDsi4KGuTMorsTQHhGBzBkMun4iDF`, I get this error message:

> We're sorry, a server error occurred. Please wait a bit and try again.

When I try to load the connector, I get this message on the Data Studio UI while accessing the connector:

> There was an error retrieving this Add-on's configuration

The same happens if I add the code from `/dist` to the Data Studio connector.

All these errors are gone after I remove either the library from the Resoures / Libraries menu or the .gs file that was added directly from the `/dist` directory of this repository.

This behavior is independent from what I set in `getAuthType()`. Even with `NONE` I get the error messages above.

I try to use this library to use the Analytics Management API v3

Thanks in advance for every help!

**Comment by duracelltomi** [comment]
I investigated this further and it turned out that the UrlFetchApp.fetch() call is causing the issue. 

I have included this in the appscript.json file:

```
"oauthScopes": [
    "https://www.googleapis.com/auth/script.external_request"
  ],

```

... still it does not seem to work

**Comment by duracelltomi** [comment]
It might be related to this issue?
https://issuetracker.google.com/issues/109921737

> Scope https://www.googleapis.com/auth/script.external_request responds with 404, so UrlFetchApp doesn't work
> 
> To reproduce, just open in any browser:
> https://www.googleapis.com/auth/script.external_request 
> 
> Other scopes response normally.

**Comment by erickoledadevrel** [comment]
The scope returning a 404 is not related, and it not needed for it to work. After adding the scope to the manifest, did you update your deployment? Try running a method like `getConfig()` from the Apps Script editor and see if there are any errors.

**Comment by duracelltomi** [comment]
I am using the head deployment during dev, calling getConfig() within App Scripts Editor shows the same error message:

> We're sorry, a server error occurred. Please wait a bit and try again

**Comment by duracelltomi** [comment]
I've created a new App Script project with this oauth2 lib and while trying to run a dummy func, the Editor prompted for the external request permission.

I can not remember any such window in the mentioned project. Sorry for the noob question: how can I review access tokens for a specific app script project? Maybe resetting this so that the access request window can be shown again could solve my issue (?)

**Comment by erickoledadevrel** [comment]
The project properties dialog shows the currently configured scopes, but I wouldn't expect scope errors to lead to the "a server error occurred" error message. You can reset the authorization for a script (remove the token) by called `ScriptApp.invalidateAuth()`. You can also visit https://myaccount.google.com/permissions and revoke authorization from there.

**Comment by duracelltomi** [comment]
You were right, ScriptApp.invalidateAuth() did not solve the issue and on the account permissions page, this app script project is not listed though my test script where the consent window appeared is listed properly.

I will try to remove code function by function and maybe recreate the whole app script project

**Comment by duracelltomi** [comment]
I created a new App Scripts project and started the copy/paste of code with this oauth2 lib.
Everything worked fine, consent window was shown.

Then I setup the new App Script project to change to another Google Cloud Platform project where billing was already configured and after this move I get the `We're sorry, a server error occurred.` message again.

So this is definitely not related to this oauth2 lib.
If you have any idea what could be the solution for me, I would be grateful but we can close this ticket of course as discussion is not related to the code anymore.

**Comment by erickoledadevrel** [comment]
I just tested it out and I too get that error when I attempt to switch projects. I've raised the issue with the engineering team, but I don't know how complex the problem is to solve. In the mean time I'd advise against switching console projects, and instead see if you can just link you existing billing account to your new project.
