### ISSUE TITLE
Cache "no token" to avoid reading Properties too much

### ISSUE THREAD

**Issue by tdelmas** [gsuitedevs/apps-script-oauth2#144]
When there is no token, each time we call `Service_.prototype.hasAccess` , Properties are read.

As they are subject to rates limits and slower than Cache, unnecessary reads should be avoided.

`Storage_.prototype.getValue` could for example store (in `this.memory_` and `this.cache_`) a special value such as `"null"` (as string), and when that value is encountered, returns `null` (not a string)

**Comment by erickoledadevrel** [comment]
Thanks for the suggestion, makes sense. I sent out PR #146, please take a look.
