### ISSUE TITLE
Does Google AppScript (GAS) supports O-Auth 2.0 Implicit Grant-Type

### ISSUE THREAD

**Issue by gupta-pratik** [gsuitedevs/apps-script-oauth2#153]
Hi, 
I'm trying to create a new Gmail Addon using _Google AppScript_ and trying to access third party non-google Api. And for that I am using **O-Auth 2.0 Implicit Grant-Type** for authentication purpose.

This is how the AuthService looks like :

> function getOAuthService() {
>   return OAuth2.createService('Podio O-Auth')
>     .setAuthorizationBaseUrl('Base Url')
>     .setTokenUrl('Token Url')
>     .setClientId('clientId')
>     .setClientSecret(clientSecret')
>     .setParam('redirect_uri', 'https://script.google.com/macros/d/'+scriptID+'/usercallback')
>     .setScope('GLOBAL')
>     .setCallbackFunction('authCallback')
>     .setCache(CacheService.getUserCache())
>     .setParam('response_type', 'token')
>     .setParam('response_mode', 'query')
>     .setParam('state', getStateToken('authCallback')) // function to generate the state token on the fly
>     .setPropertyStore(PropertiesService.getUserProperties());
> }

The script correctly generates an URL that includes my redirect_uri
Auth picks up the request, generates a token, and redirects me to the scripts.google.com domain.
Once hitting scripts.google.com I am redirected to an URL that includes my custom domain.

https://script.google.com/a/macros/[custom-domain]/d/[script-id]/usercallback#access_token=[token]&expires_in=7200&token_type=Bearer&state=[state]&id_token=[token]

Which results in an error:

<img width="698" alt="screen shot 2018-10-05 at 11 41 32 pm" src="https://user-images.githubusercontent.com/22120990/46552421-44695b00-c8f8-11e8-8fec-2acda8f8dee9.png">

Here the issue is that Url is fragmented by `#` . If I replace the `#` via `?` then it works as expected.
Can anyone please tell me how can I fix this issue? If not then do I have to `Authorization code grant flow` for this purpose ? 

> Note: I have used setParam('response_type', 'token') for Implicit Grant-Type

**Comment by erickoledadevrel** [comment]
The library currently doesn't support implicit grants. This flow returns the access token directly, and is meant for client-side JavaScript applications that don't have a backend. The Podio API, which you appear to be connecting two, also supports (and recommends you use) the server-side flow which this library does support:

https://developers.podio.com/authentication/server_side
