### ISSUE TITLE
How to setup Oauth2 library in GAS WebApp to allow for multiple simultaneous user logins

### ISSUE THREAD

**Issue by ksben** [gsuitedevs/apps-script-oauth2#154]
Hello,
I am having problems isolating user Sessions upon login with the OAuth2 library in google app script WebApp.  If one user logs in to the webApp everything is ok.  If a second user opens the Webapp, the first person is shown logged in on the new users session.  If the second user logs off, both users are logged off.  I used the WebApp example you had in your apps-script-oauth2/samples/WebApp folder and it behaved identically to my WebApp.  Here are samples of my code:

```js
function doGet(e) 
{
  service=getService_GoogleServAPI(Session.getTemporaryActiveUserKey());

  if (!e.parameter['page']) {
    return HtmlService.createTemplateFromFile('MY_PAGE')
      .evaluate()
      .setTitle('MY_PAGE_TITLE')
      .setSandboxMode(HtmlService.SandboxMode.IFRAME);
  }
   else
  { 
      return HtmlService.createTemplateFromFile(e.parameter['page'])
      .evaluate()
      .setTitle(e.parameter['page'])
      .setSandboxMode(HtmlService.SandboxMode.IFRAME);
  }
}



function getService_GoogleServAPI(Sess) {
      var theEmail="";
      try{
        //theEmail=Session.getActiveUser().getEmail();
      }catch(e){console.log('error getting email in getService_GoogleServAPI e='+e)}
      return new OAuth2.createService('FusionTables')
      
      // Set the endpoint URLs.
      .setAuthorizationBaseUrl('https://accounts.google.com/o/oauth2/auth')
      .setTokenUrl('https://accounts.google.com/o/oauth2/token')

      // Set the client ID and secret.
      .setClientId(CLIENT_ID)
      .setClientSecret(CLIENT_SECRET)

      // Set the name of the callback function that should be invoked to
      // complete the OAuth flow.
      .setCallbackFunction('authCallback')

      // Set the property store where authorized tokens should be persisted.
      .setPropertyStore(PropertiesService.getUserProperties())

      // Set the scope and additional Google-specific parameters.
      //.setScope('profile')
      .setScope(scopeWebmasters)
      .setParam('access_type', 'offline')
      //.setParam('access_type', 'online')
      .setParam('approval_prompt', 'force')
      //.setParam('approval_prompt', 'auto')
      
      /* 
      removed due to issues at the home page - 
      ***IS ONLY available if user is in same domain*** 
      */
      .setParam('login_hint', theEmail);
}

/**
 * Handles the OAuth callback.
 */
function authCallback(request) {
  
  var authorized = 
  getService_GoogleServAPI(Session.getTemporaryActiveUserKey()).handleCallback(request);

  if (authorized) {
 
    var theRetEmail=getService_GoogleServAPI(Session.getTemporaryActiveUserKey()).getUserEmail();
    Logger.log("in GoogleServiceApi_001 in authCallback() theRetEmail="+theRetEmail)
    return HtmlService.createHtmlOutput("'Re-Authorization-Success!' <br><br>Please close this window and re-try your previous attempt. <br><br>Note: All Authorization is performed based on your email which is: <br>"+theRetEmail);
    
      
  } else {
    return HtmlService.createHtmlOutput('Denied. You do not have permission to view this web page.');
  }
}
```

Finally on the client side in my $(document).ready function of my homepage, i run getService_GoogleServAPI(Session.getTemporaryActiveUserKey()).hasAccess()) on the server using google.script.run on my client JavaScript call to Authenticate the user. 

I tried adding Session.getTemporaryActiveUserKey() to try to uniquely identify the package to prevent interference but i think that is ineffective because that users session is never created.  

Any ideas or recommendations on how to resolve this session mix-up?  Its especially bad because users have different permission levels and sensitive information may be released to unauthorized users if sessions are not isolated.  

I am wondering if i should eliminate the client-side call of getService_GoogleServAPI in my $(document).ready function of my client.  Only problem is, I am not sure what function to call to login (acquire a new token).

Thank you.

**Comment by erickoledadevrel** [comment]
You are storing the tokens in `UserProperties`, which usually is enough to isolate things between users. Did you deploy the web app to run as the developer (AKA you?). If so, then it will be the same `UserProperties` accessed for each end users of your web app. Would it be possible for you to deploy your web app to run as the end user?

`getTemporaryActiveUserKey()` will suffer the same problem as `UserProperties`, namely that it keys off of the user running the script.

**Comment by ksben** [comment]
Hi Eric.  Yes that resolved the issue.  Thank you.

I suspect creating a unique argument for OAuth2.createService() would probably be redundant as well.  I saw some examples where that was done but i suspect UserProperties would be enough as well.
