### ISSUE TITLE
eBay API Redirect URI 

### ISSUE THREAD

**Issue by mcready85** [gsuitedevs/apps-script-oauth2#156]
eBay's API has its own Redirect URL or RuName, as they call it, and that is expected in place of the https://script.google.com/macros/d/{SCRIPT ID}/usercallback URL. Is there a workaround for this issue or will eBay's API not work within the scope of a Google script?

**Comment by tistudios** [comment]
please post a screenshot

**Comment by mcready85** [comment]
Hope these screenshots help

![capture1](https://user-images.githubusercontent.com/44510698/47806591-837ca780-dd10-11e8-8357-4891a8a35769.PNG)

This shows script code is fine and asks for access to use account

![capture2](https://user-images.githubusercontent.com/44510698/47806622-942d1d80-dd10-11e8-82cb-60d6f2bd2124.PNG)

This is pulled from eBay's API documentation, also available here: https://developer.ebay.com/api-docs/static/oauth-qref-auth-code-grant.html

![capture3](https://user-images.githubusercontent.com/44510698/47806668-adce6500-dd10-11e8-9ed0-7dfb02e40e9e.PNG)

This is what is being logged when running the run function. If I replace the redirect_uri field in URL with my supplied RuName from eBay, script authenticates just fine, like so.

![capture4](https://user-images.githubusercontent.com/44510698/47806889-2503f900-dd11-11e8-8d3d-8e9acf545945.PNG)

**Comment by tistudios** [comment]
If it has been authorized then you can make API Calls no?

**Comment by mcready85** [comment]
No, the script isn't authorizing it. To clarify, eBay expects the RuName that is generated when you sign up and get credentials for their API as the uri_redirect. I manually changed the value for that and pasted the complete URL into a web browser to make sure all other variables are correct. My question is, is there a workaround for this to use eBay's API via Google Scripts using 0Auth2 authorization?

**Comment by erickoledadevrel** [comment]
I see, the Ebay OAuth flow expects the name (ID) of a Redirect URL configuration in the `redirect_uri` parameter instead of the actual URL itself. A quick hack to enable this is to override the `getRedirectUri()` method of library:

```js
OAuth2.getRedirectUri = function() {
 return 'whatever you want'; 
}
```

I could add a configuration option that allows you to override the default redirect URI for cases like this, although it seems rare.

**Comment by erickoledadevrel** [comment]
I've cut a new release of the library that allows for arbitrary redirect URIs without needing to use the hack above. When configuring the service, use the method `setRedirectUri()` to configure the value you want:

```js
// Set the redirect URI to the RuName (eBay Redirect URL name).
.setRedirectUri(RU_NAME)
```

A full sample for eBay's auth flow is available here: https://github.com/gsuitedevs/apps-script-oauth2/blob/master/samples/eBay.gs
