### ISSUE TITLE
Question about multiple OAuths

### ISSUE THREAD

**Issue by kenman345** [gsuitedevs/apps-script-oauth2#158]
I am wanting to use a google Script to be triggered off a Google Form submission that can interact with Github, Twitter and Facebook.

It appears that Github and Facebook both use the /usercallback redirecturi because its hardcoded to the OAuth2.gs file as part of the return for that function. 

Is that just a built in Google Script method that has to be the one called? I'm trying to understand as I work through Github integration first that when I get to Facebook it wont be a problem. It appears that when I set up Github, I tried setting the authcallback to something specific to Github, but perhaps I was doing that wrong?

Just looking ahead and wanted to understand how to setup two OAuth connections for a single App so I can be prepared when I move to that stage of my development.

EDIT:
I noticed a lack of Samples of this type of scenario, which might be helpful for people in the future.

**Comment by erickoledadevrel** [comment]
The redirect URI will be the same for all OAuth2 services that a script has configured. Each service should probably use a different callback function though, since you may want to have different logic in there. Which callback function to use is encoded in the state token, not the redirect URI. Does that clear it up?

**Comment by kenman345** [comment]
I am confused since the only thing I did was try changing what I set the authorizationcallback function to and made a copy of the function and renamed it to match my new function name i defined in the callback and it would not approve of such a change saying I had a mismatch in the authorization callback

**Comment by erickoledadevrel** [comment]
I'm not sure what happened there, but it sounds like the redirect URL you configured in the OAuth provider didn't match, which is independent of Apps Script or this library. If you find a bug, or have a suggestion how how to improve the documentation, let me know.
