### ISSUE TITLE
OAuth Authentication 2.0 Community Connector Data Studio/Apps Scripts

### ISSUE THREAD

**Issue by a2desenvolvimento** [gsuitedevs/apps-script-oauth2#160]
I am not able to finalize the authentication process in data studio, it is not calling the Success screen, function Authcallback (). The Authorize button appears on the Data Studio screen plus does not update and allows the connection. documentation, would you be able to use this API https://developers.contaazul.com/#, with data studio? Follow the code! I've already added the library to the script.OAuth2 documentation, https://github.com/gsuitedevs/apps-script-oauth2.

```js
function getOAuthService(){ 
   clearProperties(userProperties);
   var scriptProps = PropertiesService.getScriptProperties();
   credenciais = new getConta();
   var clientId = credenciais.CLIENT_ID;
   var clientSecret = credenciais.CLIENT_SECRET;
   //var objSetHash = new setHash();   
   var State = setHash();   
  return OAuth2.createService('ContaAzul')
  .setAuthorizationBaseUrl('https://api.contaazul.com/auth/authorize?state='+ State)
  .setTokenUrl('https://api.contaazul.com/oauth2/token')
  .setClientId(clientId)
  .setClientSecret(clientSecret)
  .setPropertyStore(PropertiesService.getUserProperties())
  .setCache(CacheService.getScriptCache())
  .setScope('sales')       
  .setCallbackFunction('authCallback')
  // Set the response type to code (required).
  .setParam('response_type', 'code');

 }
function resetOAuth(){
 var service = getOAuthService();  
 service.reset();
}
function get3PAuthorizationUrls() { 
  return getOAuthService().getAuthorizationUrl();
  //Logger.log(retorno);
  //return retorno;
}
function isAuthValid() {
 return getOAuthService().hasAccess();
  //Logger.log(acesso);
  //return acesso;
}
/*Does not enter the else*/
function authCallback(request) {
 var isAuthorized = getOAuthService().handleCallback(request);
 if (isAuthorized) {
   return HtmlService.createHtmlOutput('Success! You can close this tab.');
 } else {
  return HtmlService.createHtmlOutput('Denied. You can close this tab');
}
}
```

**Comment by erickoledadevrel** [comment]
I'm not sure why the callback URL isn't opening, but it probably has to do with your Data Studio connector setup and not this library. I'd consider asking this question on one of the [Data Studio developer support channels](https://developers.google.com/datastudio/connector/support).

As for your code, some things I notice:
- You seem to be clearing your user properties every time you call `getOAuthService()`, which will may end up breaking your auth flow.
- You have you token stored in user properties but you are caching at the script level. Use `getUserCache()` instead.

**Comment by a2desenvolvimento** [comment]
It worked, it was a stream error in the application credentials, one more question, this library does all the authentication flow, including refresh of the token, once running do not need to worry more about this stream?

**Comment by erickoledadevrel** [comment]
That's correct, the library handles refreshes of tokens. This works with most OAuth2 providers, but there are some where refresh isn't possible or it isn't possible to detect when a refresh is required.

**Comment by a2desenvolvimento** [comment]
Thanks, it was a great help!
