### ISSUE TITLE
Facebook Auth The domain of this URL isn't included

### ISSUE THREAD

**Issue by SergeyDirin** [gsuitedevs/apps-script-oauth2#164]
Hello. I am receiving the error

> Can't Load URL: The domain of this URL isn't included in the app's domains. To be able to load this URL, add all domains and subdomains of your app to the App Domains field in your app settings.

I added the following domains in Facebook App but it still not working

- datastudio.google.com
- script.google.com
- google.com

Can you please help me and show what I am doing wrong?

**Comment by erickoledadevrel** [comment]
I'm not very familiar with Facebook's requirements, but perhaps you have strict mode enabled? If so, you may need to enter the full redirect URI, and not just the domain:

https://developers.facebook.com/blog/post/2017/12/18/strict-uri-matching/

**Comment by SergeyDirin** [comment]
Thank you for quick response.

I used the redirect URI as suggested in this library
https://script.google.com/macros/d/{SCRIPT ID}/usercallback

I checked it with Redirect URI validator and it showed that my URI is valid.

**Comment by SergeyDirin** [comment]
Yes I found it )). 
The problem was that I used the name of my callback function authCallback as a "usercallback" part of redirect URI. So for me the redirect URI was
https://script.google.com/macros/d/{SCRIPT ID}/authCallback 
That is a mistake.

Thank you for your help.
