### ISSUE TITLE
Add the ability to add additional JWT claims, to support retrieving service account ID tokens

### ISSUE THREAD

**Issue by roudy16** [gsuitedevs/apps-script-oauth2#165]
I'm not sure if getting id tokens from Google is in the scope of this library but it seems like maybe it is. There is documentation on how to get id tokens for gcp service accounts in other environments [here](https://cloud.google.com/iap/docs/authentication-howto#authenticating_from_a_service_account). My AppMaker app needed to make a request to a service that is behind an Identity-Aware Proxy and I thought there would be some way to get this library to do what I wanted. After spending sometime sifting through the examples in the documentation I linked earlier and the source for this project I'm fairly confident that getting the id tokens for service accounts is not supported. I ended up using the source from this project as inspiration to implement fetching an id token myself. I think it would be useful if this library could support getting those tokens for service accounts.

My implementation is rough, the credential variable is the private service account JSON that's given to you when you create a service account in GCP. Here's what my implementation looks like:

```
function getServiceAccountCredential_() {
  var key = "service-cred";
  var props = PropertiesService.getScriptProperties();
  var credString = props.getProperty(key);
  
  if (!credString) {
    throw new Error("Couldn't find service account credential in script properties using key: " + key);
  }
  
  var cred = JSON.parse(credString);
  return cred;
}

function createJwt_(cred) {
  var header = {
    alg: 'RS256',
    typ: 'JWT',
    kid: cred["private_key_id"]
  };
  var now = new Date();
  var expires = new Date(now.getTime());
  expires.setMinutes(expires.getMinutes() + 60);
  var claimSet = {
    iss: cred["client_email"],
    sub: cred["client_email"],
    aud: cred["token_uri"],
    exp: Math.round(expires.getTime() / 1000),
    iat: Math.round(now.getTime() / 1000),
    target_audience: "105555555555-kdumbekekekdjdjfhaasdfaadsfke.apps.googleusercontent.com",
  };

  var toSign = Utilities.base64EncodeWebSafe(JSON.stringify(header)) + '.' +
      Utilities.base64EncodeWebSafe(JSON.stringify(claimSet));
  var signatureBytes =
      Utilities.computeRsaSha256Signature(toSign, cred["private_key"]);
  var signature = Utilities.base64EncodeWebSafe(signatureBytes);
  return toSign + '.' + signature;
}

function fetchIdToken_() {
  var cred = getServiceAccountCredential_();
  var jwt = createJwt_(cred);
  var payload = {
    assertion: jwt,
    grant_type: 'urn:ietf:params:oauth:grant-type:jwt-bearer'
  };
  
  var headers = {
    'Accept': 'application/json'
  };
  
  var resp = UrlFetchApp.fetch(cred['token_uri'], {
    method: 'post',
    headers: headers,
    payload: payload,
    muteHttpExceptions: true
  });
  
  try {
    var token = JSON.parse(resp.getContentText());
    return token["id_token"];
  } catch (e) {
    throw new Error('Token response not valid JSON: ' + e);
  }
}

```

**Comment by erickoledadevrel** [comment]
Thanks for sharing! It seems like we could build this into the library by adding a `setAdditionalClaims()` method to the `Service` class, that allowed you to set the `target_audience` claim:

```js
  .setAdditionalClaims({
    target_audience: CLIENT_ID
  })
```

Then you could get the ID token using existing methods:

```js
if (service.hasAccess()) {
  return service.getToken().id_token;
}
```

Would you be up for putting together a pull request to add this feature?

**Comment by roudy16** [comment]
Sure, I can invest some time over the holidays.
