### ISSUE TITLE
label:question TLS (1.2 or higher) Certificate

### ISSUE THREAD

**Issue by sl5net** [gsuitedevs/apps-script-oauth2#168]
I want/need to install an TLS (1.2 or higher) Certificate.

I have probably the Certificate. (My FileName i got looks like apt12345678.p12).

How could i copy the Certificate in my Apps Script and use with your fabulous script?

Docu of my customer says: "The connection to the authorization server is established using Mutual SSL."

**Comment by erickoledadevrel** [comment]
Unfortunately Apps Script's `UrlFetchApp`, which this library uses, doesn't allow for custom TLS certificates to be used. Without that functionality this library won't be able to support that OAuth2 flow. Information on how to file an Apps Script feature request can be found here:

https://developers.google.com/apps-script/support#missing_features
