### ISSUE TITLE
Is there a way to access protected deployed web apps without logging in (with token)?

### ISSUE THREAD

**Issue by majestique** [gsuitedevs/apps-script-oauth2#169]
Is there a way where I can access a deployed protected web app such as with a link: `https://script.google.com/macros/s/#######/exec` without having to log in? Perhaps with an access token? like `https://script.google.com/macros/s/#######/exec?access_token=23423asldkfjsdf`? It seems there always has be a user login to access web app.

**Comment by erickoledadevrel** [comment]
This seems to be a question about Apps Script, and not this library in particular. In general if you wish to call an Apps Script from another system we recommend you use the Apps Script API:

https://developers.google.com/apps-script/api/how-tos/execute
