### ISSUE TITLE
Gmail API -   insufficient_scope

### ISSUE THREAD

**Issue by anedando** [gsuitedevs/apps-script-oauth2#172]
I'm  trying setup app script for work with gmail api for set signature to all domain's users.  but allways service response this:

```
"error": {
  "errors": [   {
    "domain": "global",
    "reason": "insufficientPermissions",
    "message": "Insufficient Permission"
   }  ],
  "code": 403,
  "message": "Insufficient Permissi...

```

and header 

_`([({'Transfer-Encoding':"chunked", Server:"GSE", 'X-Content-Type-Options':"nosniff", 'WWW-Authenticate':"Bearer realm=\"https://accounts.google.com/\", error=insufficient_scope, scope=\"https://mail.go...)`_

-I follow the oauth2 example. 
-I created a service account in api console and grant wide-domain delegation to my gsuite domain. 
-I add client id and scopes in security option form gsuite domain console.
-I add all necessary scopes in manifests (appscript.json)

service creation work well, but api don't accept requests.  
What can be wrong?  Any Idea ? (I do not find anything else to check). Thank to all 

This is the code:

```
function` setSignature(service,userEmail,html) {
    var urlsig = 'https://www.googleapis.com/gmail/v1/users/'+userEmail+'/settings/sendAs/'+userEmail;
  var data = {'signature': 'aca va un html de la firma' }  ; 
    
    var options = {
      'headers': {'Authorization': 'Bearer '+ service.getAccessToken(),
                 'contentType': 'application/json',
                  'Accept': 'application/json'},
      'method' : 'PATCH',
      'muteHttpExceptions' : true ,
      'payload' : JSON.stringify(data)   };
  
     var response = UrlFetchApp.fetch(urlsig, options);
     Logger.log(response.getContentText());
     Logger.log(response.getAllHeaders().toSource());

    return



function GetService() {
  var service = OAuth2.createService('GmailAPI20190301')

  .setAuthorizationBaseUrl('https://accounts.google.com/o/oauth2/auth')
  .setTokenUrl('https://accounts.google.com/o/oauth2/token')
  .setPrivateKey(PRIVATE_KEY)
  .setIssuer(CLIENT_EMAIL)
  .setSubject(USER_EMAIL)
  .setScope( 'https://www.googleapis.com/auth/gmail.settings.sharing','https://www.googleapis.com/auth/gmail.settings.basic','https://www.googleapis.com/auth/drive','https://www.googleapis.com/auth/script.external_request','https://www.googleapis.com/auth/spreadsheets', 'https://mail.google.com/')
  .setPropertyStore(PropertiesService.getUserProperties());

return service;
  }

```

and this is manifests file:

```

{
  "timeZone": "America/Argentina/Buenos_Aires",
  "dependencies": {
    "enabledAdvancedServices": [{
      "userSymbol": "Drive",
      "serviceId": "drive",
      "version": "v2"
    }, {
      "userSymbol": "Gmail",
      "serviceId": "gmail",
      "version": "v1"
    }],
    "libraries": [{
      "userSymbol": "OAuth2",
      "libraryId": "1B7FSrk5Zi6L1rSxxTDgDEUsPzlukDsi4KGuTMorsTQHhGBzBkMun4iDF",
      "version": "31",
      "developmentMode": true
    }]
  },
  "exceptionLogging": "STACKDRIVER",
  "oauthScopes": ["https://www.googleapis.com/auth/drive", "https://www.googleapis.com/auth/gmail.settings.basic", "https://www.googleapis.com/auth/script.external_request", "https://www.googleapis.com/auth/gmail.settings.sharing", "https://www.googleapis.com/auth/spreadsheets", "https://mail.google.com/"]
}


```

**Comment by tehhowch** [comment]
Your first function's code does not appear to be syntactically correct.  But, assuming that the `GetService` function is properly included here in your question, the issue is in your use of the `.setScope` method.

Per the library source code:
https://github.com/gsuitedevs/apps-script-oauth2/blob/6802ca55fc4d07747dfa8229e410b3cf750b426f/src/Service.js#L219-L232

we can see that only the first two arguments are consumed, and only if the first argument is of type array.

Thus, either join the scopes yourself, into a single string, or pass an array of the required scopes:

```
  ...
  .setScope([
    "https://www.googleapis.com/auth/gmail.settings.sharing",
    "https://www.googleapis.com/auth/gmail.settings.basic",
    ...
  ])
  ...
```
Otherwise you are creating the service with only the first scope--`gmail.settings.sharing`.

**Comment by anedando** [comment]
Effectively, this solve the issue.
Now, I must correct my function, but that is another story  ; -)

Thank you for reply and support.
Regards
