### ISSUE TITLE
Inability to have multiple connections to an external API simultaneously

### ISSUE THREAD

**Issue by jranzenberger** [gsuitedevs/apps-script-oauth2#174]
I see that the library expects the client secret and client ID to be passed as hard variables to establish a "service" object in the getService() function-

Is there a reason why these aren't passed as parameters so, as the apps script developers, we could manage the establishment of any number of service objects (users of the software,) by entering different credentials as we like?

**Comment by erickoledadevrel** [comment]
Those values do need to be passed into the `Service` object, but you don't have to hard code them as I show in the samples. You could load them from Properties or even an external server. That said, client ID and client secret are meant to identify the _application_, not the user. Each user gets a unique access token, but the same client ID and secret should be throughout.

**Comment by jranzenberger** [comment]
Ah I see, sorry for the misinterpretation. I was trying to determine if the library had the ability to facilitate multiple users at the same time, and my question was pointed at the wrong specific details. This question still remains for me, however: Does this library allow for multiple user connections to the API to exist at the same time (and those credentials automatically managed and updated)? Or is the service object created for the user operating in the moment, and a connection thereby only existing every time the getService() function is called?

**Comment by erickoledadevrel** [comment]
Sorry for the slow reply, and the answer is yes, it does. There are two things that control the connection:

1. The name of the service.
1. The property store used.

Usually you keep the name of the service the same for all users, and just change it if you are connecting to two or more OAuth providers. But if you set the property store to user properties, then each user will have their own tokens, AKA connection.
