### ISSUE TITLE
Apps Script Oauth2

### ISSUE THREAD

**Issue by Kjacoby** [gsuitedevs/apps-script-oauth2#183]
Hi, 

I can't seem to get the oauth2 flow working properly for my account. I've done all the steps outlined in https://github.com/gsuitedevs/apps-script-oauth2. Including the client ID/Secret and setting up the API console access to the service.

Every time I run the script I get an error:

Error: Access not granted or expired. (line 454, file "Service", project "OAuth2")

I've already used the same ClientID/Secret in google's ouathplayground and have had success, not sure why it is not working with this ouath2 library. 

Any ideas? 

```
function getGmbService() {
  
  // Create a new service with the given name. The name will be used when
  // persisting the authorized token, so ensure it is unique within the
  // scope of the property store.
  
  return OAuth2.createService('gmb')
  // Set the endpoint URLs, which are the same for all Google services.
  .setAuthorizationBaseUrl('https://accounts.google.com/o/oauth2/auth')
  .setTokenUrl('https://accounts.google.com/o/oauth2/token')
  
  // Set the client ID and secret, from the Google Developers Console.
  .setClientId('...')
  .setClientSecret('...')
  
  // Set the name of the callback function in the script referenced
  // above that should be invoked to complete the OAuth flow.
  .setCallbackFunction('authCallback')
  
  // Set the property store where authorized tokens should be persisted.
  .setPropertyStore(PropertiesService.getUserProperties())
  
  // Set the scopes to request (space-separated for Google services).
  .setScope('https://www.googleapis.com/auth/plus.business.manage')
  
  // Below are Google-specific OAuth2 parameters.
  
  // Sets the login hint, which will prevent the account chooser screen
  // from being shown to users logged in with multiple accounts.
  .setParam('login_hint', Session.getActiveUser().getEmail())
  
  // Requests offline access.
  .setParam('access_type', 'offline')
  
  // Forces the approval prompt every time. This is useful for testing,
  // but not desirable in a production application.
  .setParam('approval_prompt', 'force');
}

function showSidebar() {
  var gmbService = getGmbService();
  if (!gmbService.hasAccess()) {
    var authorizationUrl = gmbService.getAuthorizationUrl();
    var template = HtmlService.createTemplate(
      '<a href="<?= authorizationUrl ?>" target="_blank">Authorize</a>. ' +
      'Reopen the sidebar when the authorization is complete.');
    template.authorizationUrl = authorizationUrl;
    var page = template.evaluate();
    DocumentApp.getUi().showSidebar(page);
    Logger.log("Access Granted")
  } else {
    Logger.log("No Access")
  }
}

function authCallback(request) {
  var gmbService = getGmbService();
  var isAuthorized = gmbService.handleCallback(request);
  if (isAuthorized) {
    return HtmlService.createHtmlOutput('Success! You can close this tab.');
  } else {
    return HtmlService.createHtmlOutput('Denied. You can close this tab');
  }
}

//Oauth2 Flow Finish

//Request
function makeRequest() {
  var gmbService = getGmbService();
  var payload = {
    "pageSize": 5,
    "ignoreRatingOnlyReviews": true
  }
  
  var options = {
    "headers": {
      "Authorization": 'Bearer ' + gmbService.getAccessToken()
    },
    "method": 'GET',
    "payload": payload,
  };
  
  var response = UrlFetchApp.fetch("https://mybusiness.googleapis.com/v4/accounts/.../locations/.../reviews", options)
  Logger.log(response);
  // sortResponse(response)
  
}
```

**Comment by polo-man** [comment]
Good evening, Eric!

I got the same problem - line 454...
Here's my attempt:
`function delteFile(myFileName) {
 
  var clientId='-------------------';
  var clientSecret='-------------------'; //*/

  var service = getStorageService(clientId, clientSecret);
  Logger.log(service.hasAccess()); // returns false
  var token=service.getAccessToken();

function getStorageService(clientId, clientSecret) {

  return OAuth2.createService('storage')
      .setAuthorizationBaseUrl('https://accounts.google.com/o/oauth2/auth')
      .setTokenUrl('https://accounts.google.com/o/oauth2/token')
      .setClientId(clientId)
      .setClientSecret(clientSecret)
      //.setCallbackFunction('authCallback')
      .setPropertyStore(PropertiesService.getUserProperties())
      .setScope("https://www.googleapis.com/auth/devstorage.read_write https://www.googleapis.com/auth/script.external_request")
      //.setParam('login_hint', Session.getActiveUser().getEmail())
      //.setParam('access_type', 'offline')
      //.setParam('prompt', 'consent')
      .setParam('approval_prompt', 'auto');
};
  
  function authCallBack () {
    return;
  }
};`

I don't need any authorization dialog, just want to delete some file at Google Cloud Storage through Apps Script.
Can I at least find out does it exactly access not granted or token is expired?

**Comment by erickoledadevrel** [comment]
As per the error message, this error indicates that the service doesn't have access at the time you are trying to get the access token:

https://github.com/gsuitedevs/apps-script-oauth2/blob/master/src/Service.js#L454

@Kjacoby - Did you run the `showSidebar()` function and go through the auth flow?

@polo-man - When using a client ID and secret you need to approve the authorization dialog or it won't work. If you are trying to call the Cloud Storage API then you might be better off using the service account flow:

https://github.com/gsuitedevs/apps-script-oauth2/blob/master/samples/GoogleServiceAccount.gs
