### ISSUE TITLE
Getting wrong Cloud Platform Project ID after changing from default appscript project

### ISSUE THREAD

**Issue by stephengale801** [gsuitedevs/apps-script-oauth2#184]
Working with the Hangouts Chat Bot template to add access to chat.bot REST API.  Prior to adding this library, I had changed the Project from within the "Resources > CloudPlatform Project" menu.

Now after adding the Library and Template, running the default "sendPushMessage()" function returns the following error:
`{"error":{"code":403,"message":"Hangouts Chat API has not been used in project 879964091322 before or it is disabled. Enable it by visiting https://console.developers.google.com/apis/api/chat.googleapis.com/overview?project=879964091322 then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry.","status":"PERMISSION_DENIED","details":[{"@type":"type.googleapis.com/google.rpc.Help","links":[{"description":"Google developers console API activation","url":"https://console.developers.google.com/apis/api/chat.googleapis.com/overview?project=879964091322"}]}]}}`

Looking at the CloudProject that is now associated with the project, it is completely different and attempting to reassociate with the referenced project id returns an error.

**Comment by stephengale801** [comment]
Making a copy of the project worked, but the bug/issue is related to when the Cloud Platform Project is changed.

**Comment by erickoledadevrel** [comment]
This is working an intended. As per [the documentation](https://developers.google.com/apps-script/guides/cloud-platform-projects#enabling_an_api_in_a_standard_gcp_project), Google APIs need to manually enabled for standard GCP projects. Once you've switched off of the default GCP project it's no longer possible to get it back.

**Comment by stephengale801** [comment]
Yes, however the oAuth script sees the original project I'd rather than the
associated script.

**Comment by erickoledadevrel** [comment]
The library just uses the client ID and client secret you pass to it. If you change projects, you'll need to create a new client ID and secret in that project and then update your code.

**Comment by stephengale801** [comment]
Hi Eric,
Seems to be sorted now.  It may have been a propagation issue.  I had
changed the project earlier, that evening and was getting a returned error
message pointing to the incorrect cloud console URL.  After retrying this
morning, the API returns the expected results.
Thanks for your help for maintaining this project.
