### ISSUE TITLE
Please update documentation to explicitly say that OAuth2 Implicit Flow is not supported

### ISSUE THREAD

**Issue by maracharnell** [gsuitedevs/apps-script-oauth2#186]
The fact that Implicit Flow isn't supported is explained in one of the [closed issues](https://github.com/gsuitedevs/apps-script-oauth2/issues/153), but I can't find it mentioned at all in the documentation / downloaded files. 

In my case, I didn't think to check the "issues" list until after I'd been working on the problem for a few days. I'm new enough to OAuth and GAS that I couldn't tell at first whether I was using the library wrong or the library simply didn't support what I was doing.  

Adding the information about Implicit Flow to the documentation would probably save time for other folks, too.

**Comment by erickoledadevrel** [comment]
Done!
