### ISSUE TITLE
"We're Experiencing Some Problems"

### ISSUE THREAD

**Issue by atcobb01** [gsuitedevs/apps-script-oauth2#187]
Thanks for the code.  I've done everything n the code: added the library, entered my sandbox info (client ID and Secret), run the getRedirectURI and pasted it into the redirect URI in the Keys tab.  Nothing seems to work - still get the "We're Experiencing problems.  Please Try Again Later" message.  I get as far as calling hasAccess, which fails, then I click the link "Open the following URL and re-run the script", then get the "We're sorry" error page.

Any tips on breaking down the steps using the Logger or some other method so I can see why it's not working/where it fails?  I have a feeling it's the redirect URI (what else could it be?), so any tips on logging the callback (I have a Logger.log("In the callback"), but it never gets executed)?

Below are my variables:

var CLIENT_ID = '...'; // Got from Quickbooks Developer Console
var CLIENT_SECRET = '...'; // Got from Quickbooks Developer Console
var BASE_AUTH_URL = 'https://appcenter.intuit.com/connect/oauth2';
var TOKEN_URL = 'https://oauth.platform.intuit.com/oauth2/v1/tokens/bearer';
var API_SCOPE = 'com.intuit.quickbooks.accounting';
var REDIRECT_URI = 'https://script.google.com/macros/d/.../usercallback'; // Generated using the logRedirectUri() 
var RESPONSE_TYPE = 'code';

TIA

**Comment by erickoledadevrel** [comment]
Is the `authCallback` function being executed at all, or is it failing before that?

**Comment by atcobb01** [comment]
Well, here's the sequence of events:

   - run() function is called initially
   - which calls the getService() function
   - which returns the service object.  I'm assuming the callback should
   happen at this point, which it doesn't - at least I think it doesn't
   because I have a breakpoint in the callback function which is never reached.
   - After the getService function returns inside the run() function, the
   hasAccess() function is called, which return a false, which is when the
   authorizationURL is provided.


Make sense?

Andy

**Comment by erickoledadevrel** [comment]
No, I mean after you open the URL and approve access (and then get the error), can you determine if the `authCallback` function (that should get triggered) is run? If you open the [Apps Script dashbaord](https://script.google.com) you can see the executions.

**Comment by atcobb01** [comment]
If I look under "M Executions" in the dashboard, the callback is never run.

Andy

**Comment by atcobb01** [comment]
By the way, I can't even get the playground to work.  I add an app, pick
Accounting scope, then go straight to playground (with out changing the
default playground redirect URI on the Keys tab), pick Accounting scope,
then press Get Authorization Code and I get the same error screen.

Andy

**Comment by erickoledadevrel** [comment]
If that's the case then it sounds like something is wrong with their sandbox environment, and not your Apps Script code. Once you can get their playground working then dive back into Apps Script again.

**Comment by atcobb01** [comment]
Got it working.  Apparently i had more than one account open in my
browser.  Incognito worked, so I logged out, closed the browser and
re-logged it, then it worked.

Andy
