### ISSUE TITLE
smartsheetTokenHandler

### ISSUE THREAD

**Issue by jonathandavis96** [gsuitedevs/apps-script-oauth2#188]
Hi, would you explain where the smartsheetTokenHandler comes from? I cannot find it in your documentation.

**Comment by erickoledadevrel** [comment]
There is some information in the README here:

https://github.com/gsuitedevs/apps-script-oauth2#modifying-the-access-token-payload

**Comment by jonathandavis96** [comment]
This does not indicate where the token handler comes from

**Comment by erickoledadevrel** [comment]
What do you mean "comes from"? A token handler for the SmartSheet API is defined here:

https://github.com/gsuitedevs/apps-script-oauth2/blob/master/samples/Smartsheet.gs#L73

**Comment by jonathandavis96** [comment]
Thanks so much for your timely responses. My issue is that when I run the run() function it gives me a URI to follow. When I go to the suggested URI, it says "The redirect URI is missing or invalid" and I can't figure out why.

**Comment by erickoledadevrel** [comment]
I'm not sure either. Most likely you need to set the correct redirect URL in the OAuth providers config screen.

**Comment by jonathandavis96** [comment]
Do you have any idea how I might generate that? Sorry I don't know where to look as I've never done this before

**Comment by erickoledadevrel** [comment]
I think this is what you need to follow:

http://smartsheet-platform.github.io/api-docs/#register-your-app-using-developer-tools
