### ISSUE TITLE
Error: Access not granted or expired. (line 454, file "Service", project "OAuth2")

### ISSUE THREAD

**Issue by anttinylund** [gsuitedevs/apps-script-oauth2#192]
Hi,

I have exhausted all the resources (past issues, related SO posts, Google search results) so you are my last hope.

Most likely this is some basic setting error or some mistake in the process of creating a project and credentials put I just can't figure out where it is.

I'm trying to connect to Search Console and everything goes fine until it is time to get the token.

I have changed this based on one of the issues solved:
 .setParam('approval_prompt', 'auto');

This is my manifest file:
 "oauthScopes": [
    "https://www.googleapis.com/auth/webmasters",
    "https://www.googleapis.com/auth/script.external_request",
    "https://www.googleapis.com/auth/userinfo.email"
  ],

callback URL is set, API is enabled.

Can you help me to debug further?

Thanks!

**Comment by erickoledadevrel** [comment]
If you just need an additional Google scope, then you don't need to use this library at all. Simply add the scope to your manifest (which you already have) and then use `ScriptApp.getOAuthToken()` to retrieve the token the script is using, and then pass that in a `UrlFetchApp.fetch()` request to the API.
