### ISSUE TITLE
Error invalid_grant

### ISSUE THREAD

**Issue by kwiesmueller** [gsuitedevs/apps-script-oauth2#193]
I deployed an internal Gmail Addon using this library to communicate with our backend behind Google IAP.
With me everything works fine, but not that I published it I was able to test with other users and everyone gets an error when sending an api request through the IAP (after successful auth) which is being logged as follows:

```
Error retrieving token: invalid_grant, Bad Request at [unknown function](Service:526) at [unknown function](Service:501) at [unknown function](Service:399) at authCallback(iap:94)
```

I don't have a clue why, when I try with my account everything is great. Even if I force myself to re-login etc. It just works, but every other account doesn't.

**Comment by erickoledadevrel** [comment]
My guess is that you need to add these new users to your IAP configuration with the role "IAP-secured Web App User". You can likely add your whole domain / organization at once, or limit it to only certain teams or individuals.

**Comment by kwiesmueller** [comment]
I figured it out now...
The script was running as myself as I did not define it in the manifest, to run as the user.
This caused the grant to be invalid.

Would this be something to add to the documentation? I did not expect the Add-on gets run as myself for everybody tbh.
I know that is possible, but was surprised by the default and for oauth this seems important.

**Comment by erickoledadevrel** [comment]
Strange, I didn't think it's possible to have an add-on run as yourself. What settings exactly let to that behavior?

**Comment by kwiesmueller** [comment]
It's in this page: https://developers.google.com/apps-script/concepts/manifests
webapp.executeAs
I set the field to USER_ACCESSING and it worked.

**Comment by erickoledadevrel** [comment]
That's the web app settings, it doesn't affect add-ons. Glad you do it to work though.
