### ISSUE TITLE
Forwarded after reset()

### ISSUE THREAD

**Issue by scriptPilot** [gsuitedevs/apps-script-oauth2#194]
Thanks for the helful piece of code!

Unfortunately I have an issue with the `reset()` function.
The user is forwarded to URL `https://n-...-script.googleusercontent.com/userCodeAppPanel#`.

But what I want to do is to sign out and return some code to the HTML page.

**index.html**
```html
<!DOCTYPE html>
<html>
  <head>
    <base target="_top">
  </head>
  <body onload="getContent()">
    <script>
      function signOut() {
        google.script.run.withSuccessHandler(showContent).signOut()
      }
      function showContent(content) {
        document.getElementById('app').innerHTML = content
      }
    </script>
    <div id="app"><a onclick="signOut()">sign out</a></div>
  </body>
</html>
```

**signOut.gs**

```js
function signOut() {
  var driveService = getDriveService()
  driveService.reset()
  return 'Signed out'
}
```

**Comment by erickoledadevrel** [comment]
The problem is that if you don't return `false` in your anchor's `onclick`, then the inner iframe of the page is navigated to a blank page (since you have no `href` set). Either return `false` in your `onclick` or use a button instead.
