### ISSUE TITLE
Issue of INVALID_TOKEN after one hour in samples/ZohoCRM.gs 

### ISSUE THREAD

**Issue by pankajk79** [gsuitedevs/apps-script-oauth2#197]
I am trying to use this library to connect to Zoho CRM. 

Using example code https://github.com/gsuitedevs/apps-script-oauth2/blob/master/samples/ZohoCRM.gs

Only change I made was, replaced CLIENT_ID and CLIENT_SECRET values.

Upto one hour script was giving proper result.

After one hour I got message "Request failed for https://www.zohoapis.com returned code 401. Truncated server response: {"code":"INVALID_TOKEN","details":{},"message":"invalid oauth token","status":"error"}"

Perhaps access_token could not generated using refresh_token.

I can see there is code alread added
// Set the access type to "offline" to get a refresh token.
.setParam('access_type', 'offline')

but still error of INVALID_TOKEN is repeating after each one hour.

Please help.

**Comment by erickoledadevrel** [comment]
Good catch! Although not in their documentation, it looks like you only get a refresh token when explicitly approving the scopes (Google OAuth is the same). In 7bbfffbb2434c7b788d1564cb5974c4d58d8825e I added `.setParam('prompt', 'consent')` to ensure that the user always approves the scopes and therefore always gets the refresh token.
