### ISSUE TITLE
There is no method to get id_token instead of access_token

### ISSUE THREAD

**Issue by mryerse** [gsuitedevs/apps-script-oauth2#199]
Our service provider requires a payload from decoded JWTs.  Calling getAccessToken() returns the access_token, however, doesn't include a payload.  In the same property is a key named id_token (from the OpenID spec) which includes a payload with who was authenticated.  Is there a built-in way to get this?  Of course I can query the properties service to get it, however, it seems that there should be some built in function that validates access is still valid, etc.  Any suggestions on how to proceed with this?  I realize this is maybe more of a how-to, however, I doubt folks on Stackoverflow will be familiar with this library.

**Comment by erickoledadevrel** [comment]
To close the loop, it was possible via `getToken().id_token`, but you recently added a dedicated `getIdToken()` method which is a shortcut for that.
