### ISSUE TITLE
Callback function not getting called

### ISSUE THREAD

**Issue by mghatiya** [gsuitedevs/apps-script-oauth2#205]
I am trying to use OAuth2 library to access Pocket APIs in my Google Scripts project that I have exposed as an add-on and running from a Google Spreadsheet.
I am getting a “Sorry, unable to open file at this time” error when my script is called back after authorisation using the redirect uri. 

My call back function doesn’t even get invoked.

I am trying to connect to Pocket APIs. Any pointers on what could be going wrong?

**Comment by mghatiya** [comment]
Thanks for the reply, Eric. I had looked at that thread. But I don't think there also people had got their issues resolved fully. There was a solution using doGet(), which you yourself suggested is more like a workaround and bypassing the callback.

In my case I realised that it was probably happening because "state" token was not being passed to the callback. My guess is that it could be because of STATE_PARAMETER_LOCATION. In Oauth2.js I see following code 

```
var STATE_PARAMETER_LOCATION = {
  /**
   * Pass the state parameter in the authorization URL.
   * @default
   */
  AUTHORIZATION_URL: 'authorization-url',
  /**
   * Pass the state token in the redirect URL, as a workaround for APIs that
   * don't support the state parameter.
   */
  REDIRECT_URL: 'redirect-url'
};
```
and
```
if (typeof module === 'object') {
  module.exports = {
    createService: createService,
    getRedirectUri: getRedirectUri,
    TOKEN_FORMAT: TOKEN_FORMAT,
    STATE_PARAMETER_LOCATION: STATE_PARAMETER_LOCATION
  };
}
```

Due to my limited knowledge of Javascript, I didn't understand how these both snippets are working. Couldn't understand how authorization URL is becoming default in first case, and how to change that. And in second snippet I don't understand what value of STATE_PARAMETER_LOCATION is being used.

Maybe Pocket API prefers the other value of STATE_PARAMETER_LOCATION than what is default here.

Either way, I tried making "state" parameter to be part of redirect URL itself. That worked. However, state token itself is not usable to me, as I can't decrypt it. So I am passing the value using getUserProperties.

I know I found somewhat hacky work-around. But that's the best I could manage with my limited understanding.

**Comment by erickoledadevrel** [comment]
The `STATE_PARAMETER_LOCATION` enum you mentioned was never implemented, and I'll clean that up. I spent some time today trying to get this library to work with the Pocket API, but it's not a great fit. Although they claim to be using "a variant of OAuth 2.0", their authorization protocol bears very little resemblance to any OAuth2 flow I know. It seems more like an OAuth 1.0 flow but with different parameter names and without signing. Although you may be able to twist and bend this library to fit, you are probably better off implementing your own custom authorization code for this API.

**Comment by mghatiya** [comment]
Thanks Eric for taking time to look into this.
