### ISSUE TITLE
too many LockService

### ISSUE THREAD

**Issue by hanguokai** [gsuitedevs/apps-script-oauth2#207]
I use this library(version 33) to call multiple apis with access token every 30 minutes. Most of the time, it is no problem, but occasionally it reports the following errors.

- There are too many LockService operations against the same script. (line 733, file "Service", project "OAuth2")
- There are too many LockService operations against the same script. (line 738, file "Service", project "OAuth2")
- Error: Access not granted or expired. (line 454, file "Service", project "OAuth2")

**Comment by erickoledadevrel** [comment]
There is a quota on the LockService, but it should be more than enough to allow for usage once every 30 minutes. If you don't think it's likely there will be more than one simultaneous execution then you could remove the lock from the service configuration.

**Comment by erickoledadevrel** [comment]
Closing due to lack of response.

**Comment by andrewschmidt-a** [comment]
@erickoledadevrel What is the quota and is it per user or per script? 

Why is it not listed in the documentation under quotas and limits?

**Comment by erickoledadevrel** [comment]
Sorry @andrewschmidt-a - I left Google 4 years ago, so your guess is as good as mine. I'm not sure the folk on the team are going to check this thread, so you may want to consider reaching out on their Discord server.
