### ISSUE TITLE
Regarding deprecation of UserProperties

### ISSUE THREAD

**Issue by alansongzoom** [gsuitedevs/apps-script-oauth2#209]
It seems that UserProperties has been deprecated recently.

https://developers.google.com/apps-script/reference/properties/user-properties
![image](https://user-images.githubusercontent.com/49182735/69394925-5b475880-0d18-11ea-895f-f3c98cfdae57.png)

and this directly disables (new) project's ability to persist user tokens

![image](https://user-images.githubusercontent.com/49182735/69394984-85991600-0d18-11ea-8b73-381220f0503c.png)

Are there any plans for migration for this library? For example, integrate with a new storage API (not sure if it exists) provided by apps script?

**Comment by contributorpw** [comment]
As you can see the lib is using `PropertiesService.getUserProperties()` [#](https://developers.google.com/apps-script/reference/properties/properties-service). It's not the same `Class UserProperties`.

**Comment by alansongzoom** [comment]
I mistook PropertiesService.getUserProperties() to return UserProperties - never mind😅.
