### ISSUE TITLE
service.hasAccess() is true, but UrlFetchApp.fetch() fails

### ISSUE THREAD

**Issue by khalilchoudhry** [gsuitedevs/apps-script-oauth2#213]
The external API I use says that 'expires_in' is 'The amount of time in seconds for the expiration of the token.'
[This code](https://github.com/gsuitedevs/apps-script-oauth2/blob/47f99625c446b7d20aaa47b81d296c992c4f9dfc/dist/OAuth2.gs#L738) in isExpired_ method always returns false.
Although 'expiresIn' is 7200 in isExpired_ method but I always get service.hasAccess() as true. Even if I run this after 24hours. I don't know why is that.

I would appreciate it if someone can point me in the right direction for this.

**Comment by erickoledadevrel** [comment]
Sorry for not replying to this issue sooner. So the problem is that it isn't expiring like you expect it to? Are you sure it's not just refreshing your access tokens after they expire? What API are you calling?

**Comment by khalilchoudhry** [comment]
Yes, the issue is that 'hasAccess' returns true just before calling UrlFetchApp.fetchAll but the response's status code is 401. The API I'm calling is [Tink](https://docs.tink.com/api/#introduction-authentication). See the logs below. I added these custom logs to oauth.gs to test.
<img width="566" alt="Screenshot 2020-03-16 at 2 22 36 PM" src="https://user-images.githubusercontent.com/29918905/76741601-a4249080-6791-11ea-8f69-28a506526c5b.png">

**Comment by khalilchoudhry** [comment]
Its been 2 days now that I last authorized with Tink. Now I will just remove the last connection and re-authorize with Tink, it will work as expected.

Also, Thanks for looking into it!

**Comment by khalilchoudhry** [comment]
`
if (!oauthService.hasAccess()) {
    throw new Error();
}
Logger.log(oauthService.getLastError());
`

So I tried to output LastError but got 'undefined'.

**Comment by khalilchoudhry** [comment]
isExpired_ method always returns false which makes [this line of code](https://github.com/gsuitedevs/apps-script-oauth2/blob/47f99625c446b7d20aaa47b81d296c992c4f9dfc/dist/OAuth2.gs#L498) in hasAccess method to return true.

The Logger output from the isExpired_ method:
{now=1.584351729E9, rslt=false, expiresTime=1.584352133E9}

'rslt' represents [this line of code](https://github.com/gsuitedevs/apps-script-oauth2/blob/47f99625c446b7d20aaa47b81d296c992c4f9dfc/dist/OAuth2.gs#L738).

**Comment by erickoledadevrel** [comment]
Interesting. Reading through their developer docs, I wonder if this is related:

> The access token will expire and needs to be refreshed for continued access. This is done with the refresh_token using the same endpoint as used when exchanging the authorization code for an access token. However, since the default behavior with Tink Link is that a user's data is only stored for 24 hours, an access_token can't be used to fetch the data when the data has been removed. Using a refresh_token won't help, since the data is gone. This means that a refresh_token is only valid during 24 hours after the initial authentication of a user.
https://docs.tink.com/resources/getting-started/retrieve-access-token#refresh-token

It could be that the refresh token is still technically valid, and is generating new access tokens, but that the data is no longer accessible because it is gone. I'm testing out the library with this API now, but it will take some time for things to expire and/or replicate your error.

**Comment by erickoledadevrel** [comment]
Re-running my script today it is indeed failing in the same way yours is. I can see that the library is correctly using the refresh token to generate a new access token, but that the API is returning a 401. It seems like my hunch was right, the library is working fine but the data just goes missing. I'll be adding a sample to the library that shows how you could handle this case.
