### ISSUE TITLE
Does this library works with Google Editor Addons as well?

### ISSUE THREAD

**Issue by yusufkhan07** [gsuitedevs/apps-script-oauth2#214]
This is a support question instead of an issue.

I have a web service that uses firebase authentication for signing in users. I would like to access my Webservice through a Google Docs add-on. I would like to know if it is possible to use this library to sign in to my Webservice through firebase.

Thank you

**Comment by sqrrrl** [comment]
Yes, it should work fine in an add-on. There's a sample (Note: not a Google sample) at https://github.com/smartsheet-samples/google-apps-standalone-addon-example that shows the oauth library used in an add-on.
