### ISSUE TITLE
Cannot finish a callback

### ISSUE THREAD

**Issue by Frelseren** [gsuitedevs/apps-script-oauth2#215]
Hello,
I go a bit stuck with the unknown issue in the callback function.

I have integrations with Facebook and Google using the current script and it works like a charm.

Recently, I added a Hubspot service. If I remember correctly, flow worked for the first time but now in every attempt, I got stuck on the redirect URL. `https://script.google.com/macros/d/131LZ0Dkorl-w6UCCBAGCPpn62jYAGtTT3LEvnkWRm9QKovJrnh_NEalE/usercallback`

It just freezes there and cannot finish the callback function.

![Screenshot 2020-01-28 at 22 01 30](https://user-images.githubusercontent.com/13909133/73300496-c716d780-4219-11ea-8f1e-594537d83dae.png)

The function is identical to the others but uses Hubspot service.

```
function hubspotAuthCallback(request) {
  var hubspotService = getHubspotService();
  var isAuthorized = hubspotService.handleCallback(request);
  if (isAuthorized) {
    var template = HtmlService.createTemplateFromFile('callback');
    template.email = Session.getEffectiveUser().getEmail();
    return template.evaluate();
  } else {
    return HtmlService.createHtmlOutput('Denied. You can close this tab');
  }
}
```

I checked the logs and the function is being called. `isAuthorized` is true, but when I return the `HtmlOutput`, nothing happens. Even if I return a template at the beginning without any other actions it never finishes. I also tried to wrap it inside `try catch` block. 

Could this be due to the fact that the request contains also a state parameter?

If anybody wants to try it out by themselves, my script is available here: https://gsuite.google.com/marketplace/app/marketing_reports/849502970392

Does anybody have ideas what might be wrong? Thanks!

**Comment by alexander-soare** [comment]
I had this same issue and and eventually figured out that I was calling `.setParam('response_type', 'token')` instead of `.setParam('response_type', 'code')` which was required by the specific api I was using. Just a warning to those who might spend a lot of time trying to debug the source code :P when that's not the real issue :P

**Comment by Frelseren** [comment]
Hi Alexander,
Thanks for the response.  Actually, I'm calling it with the `('response_type', 'code')` and everything looks fine.

It connects the source but the OAuth2 library's callback keeps running forever. If I close the callback URL and restart the add-on it will be connected and I could use the API.

It seems to me that because user callback keeps running infinitely it cannot finish the callback provided by me in the script. I tried to check the lib source code and it looks like something goes wrong inside the `handleCallback` method.

**Comment by alexander-soare** [comment]
@Frelseren Yes, `('response_type', 'code')` was right for me. I just realised I posted my comment in the wrong issue. Sorry! It was meant for https://github.com/gsuitedevs/apps-script-oauth2/issues/137

**Comment by erickoledadevrel** [comment]
@Frelseren - If `handleCallback` is completing then it doesn't seem likely that this library is the cause of the problem, as the rest of the code that executes is within your script (or within Apps Script itself). Have you tried clearing your cache or running from an incognito window?

**Comment by erickoledadevrel** [comment]
Closing due to lack of response.
