### ISSUE TITLE
No errors bu nothing

### ISSUE THREAD

**Issue by antoine-castex** [gsuitedevs/apps-script-oauth2#219]
Hello
I'm trying to re-use this library many years after first usage
I got a problem

Function called is :

```
function getProjectRights(projectID) {
  var service = getService();
  Logger.log(projectID)
  if (service.hasAccess()) {
    Logger.log("access")
    var api = "https://cloudresourcemanager.googleapis.com/v1/projects/"+projectID+":getIamPolicy";
    var headers = {
      "Authorization": " OAuth " + service.getAccessToken()
    };
    var options = {
      "headers": headers,
      "method" : "POST",
      "contentType" : "application/json",
      "muteHttpExceptions": true
    };
    var responseApi = UrlFetchApp.fetch(api, options);
    var responseApi = JSON.parse(responseApi.getContentText());
    var payload = { "bindings" : "",
                   "version" : 1}
    payload.bindings = responseApi.bindings
    Logger.log("----- "+payload)
  }
  return payload;
}
```

But my code never goes after 

`if (service.hasAccess()) {`

No error seen

How to troubleshoot ?

thanks

**Comment by antoine-castex** [comment]
Service is just typical function

function getService() {
  return OAuth2.createService('gcp')
      .setAuthorizationBaseUrl('https://accounts.google.com/o/oauth2/auth')
      .setTokenUrl('https://accounts.google.com/o/oauth2/token')
      .setClientId(CLIENT_ID)
      .setClientSecret(CLIENT_SECRET)
      .setCallbackFunction('authCallback')
      .setPropertyStore(PropertiesService.getUserProperties())
      .setScope('https://www.googleapis.com/auth/cloud-platform', 'https://www.googleapis.com/auth/cloud-platform.read-only')
      .setParam('login_hint', Session.getActiveUser().getEmail())
      .setParam('access_type', 'offline')
      .setParam('approval_prompt', 'force');

**Comment by erickoledadevrel** [comment]
The most likely situation is that the service doesn't have access anymore, and so that condition is false. You don't have any `else` condition, so nothing happens in that case. You likely need to re-approve access to your script, and you can look at the samples for how to do that.

**Comment by antoine-castex** [comment]
I'm using ScriptApp.getOAuthToken();

this is very more easy to use than this
