### ISSUE TITLE
ReferenceError: STATE_PARAMETER_LOCATION is not defined

### ISSUE THREAD

**Issue by mryerse** [gsuitedevs/apps-script-oauth2#221]
With the latest version (1.36), while instantiating the service using the sample for IAP, the following error is generated when getAuthorizationUrl():
```
ReferenceError: STATE_PARAMETER_LOCATION is not defined
    at [unknown function](OAuth2:65:32)
    at [unknown function](OAuth2:1117:5)
```

With previous versions this is not a problem.  It looks like 1.36 removed the use of STATE_PARAMETER_LOCATION, but there is still a reference to it on line 65 of OAuth2.gs.

Am I supposed to be instantiating the service differently now or is this a legit bug?

**Comment by erickoledadevrel** [comment]
Whoops! Good catch. Are you using the v8 runtime?

**Comment by erickoledadevrel** [comment]
I've published version 37 that should fix this error.

**Comment by mryerse** [comment]
Thanks for the quick response.  Yes, am using v8 runtime.
