### ISSUE TITLE
Spreadsheet copy

### ISSUE THREAD

**Issue by amorz** [gsuitedevs/apps-script-oauth2#222]
I'm having a issue with google spreadsheet. While copying the spreadsheet there is a new generated script_id that creates a new redirect url. This redirect url doesn't match the url in Moneybird api. 

Is there a possible workarround?

**Comment by erickoledadevrel** [comment]
No, not directly. If you need to have a consistent script ID and redirect URL across multiple spreadsheets, then you should create [an add-on](https://developers.google.com/gsuite/add-ons/how-tos/building-editor-addons) instead. This allows the same codebase to be used across any number of spreadsheets.
