### ISSUE TITLE
Handling multiple oauth clients within the same sheet

### ISSUE THREAD

**Issue by Blacksmoke16** [gsuitedevs/apps-script-oauth2#228]
I've seen #158, however that did not answer my question.

To give some context, I'm working on updating an add-on used to communicate with the game EVE Online's [ESI API](https://esi.evetech.net/ui/), which uses [OAuth2](https://docs.esi.evetech.net/docs/sso/web_based_sso_flow.html) of course.  

It is common for each user to have multiple characters within the game; each of which requires a separate OAuth flow.  Ideally I would create the OAuth service with the name of the character being used.  However, the problem is, unless I require the user to specify the name of the character being used before authorizing, I don't know the name of the character until the OAuth flow is completed, as the name is in the token.

I'm currently thinking about how to best handle this and wanted to see if anyone had any thoughts.

My current plan is to define a custom `handleCallback` method that returns the fetched token without saving it.  Then, define a `setServiceName` method that I'll call with the character name I retrieve from the token.  Finally, I would manually save the token within my `authCallback` method as the oauth service would be initialized with the character's name at this point.  I could then get the storage object from the oauth service to store additional data about that character.

This process would only have to happen once, as I will have access to a character name when a user goes to actually make an authenticated API call.  It would either be supplied within a function call, or use the name of the first authenticated character (their main).

The other option would be to require the user supply the name of the character they are authorizing beforehand.  However this is less than ideal, and prone to user error.  So I would like to avoid that if at all possible.

**Comment by erickoledadevrel** [comment]
Another option would be to generate your service names using arbitrary IDs. So when creating a new connection, you create a service with a new random string as the name. After they go through the authorization flow, you determine the name of the character, and then use `PropertiesService` to store which character name maps to which ID. When it's time to fetch data, look up the ID for that character and then build the service using that ID.

In general it's not too common for the same user to want to connect to the same service multiple times, hence this functionality isn't built in. But since you have control over the service names, there are a lot of options of how to build a system that does this.

**Comment by erickoledadevrel** [comment]
Some pseudo-code:

```js
function getAuthUrlForNewConnection() {
  var id = Math.random().toString().substring(2);
  var service = getService(id);
  return service.getAuthorizationUrl();
}

function getService(id) {
  return OAuth2.createService(id)
    // Configure stuff ...
}

function authCallback(request) {
  var id = request.parameter.serviceName;
  var service = getService(id);
  var authorized = service.handleCallback(request);
  if (authorized) {
    var characterName = /* Make request to your API */
    var props = Properties.getUserProperties();
    var characters = JSON.parse(props.getProperty('characters') || '{}');
    characters[characterName] = id;
    props.setProperty('characters', JSON.stringify(characters));
    return HtmlService.createHtmlOutput('Success!');
  } else {
    return HtmlService.createHtmlOutput('Denied.');
  }
}
```

**Comment by Blacksmoke16** [comment]
Ah good call!  I like this approach better.  This is what I ended up with for the record:

```TypeScript
function authCallback(request: AppsScriptHttpRequestEvent): HtmlOutput {
  const id: string = request.parameter.serviceName;

  // Fetch the oauthService used for this flow
  const oauthService = getOAuthService_(id);

  // Complete the OAuth flow
  oauthService.handleCallback(request);

  // Parse the JWT access token for some basic information about this character
  const jwtToken = ESIRequest.parseToken(oauthService.getAccessToken());
  const characterId = parseInt(jwtToken.sub.split(':')[2]);

  // @ts-ignore
  // TODO: Make a PR to update @types/google-apps-script-oauth2
  const storage: IStorage = oauthService.getStorage();

  // Fetch additional data about this character
  const affiliationData = getCharacterAffiliation_(characterId, oauthService);

  // Save data about this character with its oauth service
  storage.setValue('alliance_id', affiliationData.alliance_id);
  storage.setValue('corporation_id', affiliationData.corporation_id);
  storage.setValue('character_id', affiliationData.character_id);

  // If this character was previously authorized
  // update the ID of this character and reset the old service
  const characterMap: ICharacterMap = JSON.parse(USER_PROPERTIES.getProperty('characters') || '{}');

  // If this character is already in the map,
  // Reset/clear out data related to previous oauthService
  if (characterMap.hasOwnProperty(jwtToken.name)) {
    const previousService = getOAuthService_(characterMap[jwtToken.name]);
    previousService.reset();
    // @ts-ignore
    const previousStorage: IStorage = previousService.getStorage();
    previousStorage.removeValue('alliance_id');
    previousStorage.removeValue('corporation_id');
    previousStorage.removeValue('character_id');
  }

  // Update the UUID for this character
  characterMap[jwtToken.name] = id;
  USER_PROPERTIES.setProperty('characters', JSON.stringify(characterMap));

  // Set the main character if there is not one already
  if (!getMainCharacter()) setMainCharacter(jwtToken.name);

  return HtmlService.createHtmlOutput(`Thank you for using GESI ${jwtToken.name}!  You may close this tab.`);
}
```

One thing I thought of, should calling `.reset()` also clear out related cache/property entries?

**Comment by erickoledadevrel** [comment]
I'm glad you found a solution, and thanks so much for sharing it! It probably does make sense to clear out all the related properties in Storage when you reset a service, and I've filed #229 to address this.
