### ISSUE TITLE
Allow for multiple simultaneous user logins (not in WebApp)

### ISSUE THREAD

**Issue by e-labInnovations** [gsuitedevs/apps-script-oauth2#233]
I am trying to create APIs for an android app. The android app has unique userId for all users. 
I planning to save all details like this in a sheet (this is an object. In sheet, I use a row for it)
![](https://i.imgur.com/hwF2Vnc.jpg)
I saved the code, state, email, displayName, and AccessToken in SpreadSheet.

![image](https://user-images.githubusercontent.com/33958126/80308211-3b4a2280-87eb-11ea-8df9-98ca221d5a82.png)
 
### What is my idea?
- Create a new authorization URL using a get request to my GAS.
- Save the userId from the parameter of 
`doGet()` and state of authorization URL and return the authorization URL to the client.
- When the user authorizes, then check the `state`  variable from  [`authCallback()`](https://github.com/gsuitedevs/apps-script-oauth2#3-handle-the-callback) function and save the `code` and other details in a SpreadSheet with userID.
- If my client-side app call the GAS `doGet()` function with parameters of userId and other, then the GAS call the API and return the corresponding user Drive response to the client app

**Comment by erickoledadevrel** [comment]
From what I can tell, you don't have any functionality in Apps Script other than the OAuth2 flow. If that's the case, don't use this library or Apps Script. Instead look into use solutions like the Google Sign-in library for Android: https://developers.google.com/identity/sign-in/android

I'm not entirely sure what you are asking in your original question, but a few points:

- Don't include access tokens in your screenshots. They should be kept private, and can be used to access user data until they expire.
- You'll need to store more than just the access token if you want to refresh them when they expire. At the very least you'll need the refresh token and the time the access token was last refreshed, but it's probably better to store the entire contents of `Service.getToken()`.
- You appear to be using Google Sheets as a database, which is an antipatter, as I documented in [my blog post](https://medium.com/@eric_koleda/why-you-shouldnt-use-google-sheets-as-a-database-55958ea85d17).

**Comment by e-labInnovations** [comment]
I am trying to develop a telegram bot for Google drive. The Telegram post the update to my GAS with parameters of userID, message and much more. I want to use Google Drive API V3 managing user's google drive. I asked a telegram bot developer for help. He told me, after getting the code from the user, the store all details in their database as a JSON object. And use a Python function for calling API with that JSON object. I am planning that same way to implement in my project. Store all details in a SpreadSheet and use it.
