### ISSUE TITLE
service.hasAccess() is True, but getAccessToken() returns null

### ISSUE THREAD

**Issue by ankurs24** [gsuitedevs/apps-script-oauth2#239]
The authorization process happens smoothly and callback URL shows success. service.hasAccess() returns true, but on trying to get the access token,  service.getAccessToken() is returning null value, due to which the UrlFetch call results in **{"success":false,"message":"Authentication credentials were not provided."}**. This seems contradictory - so raising an issue. 

```
function getUserInfo() {
   var service = getInstamojoService();
   var accessToken = service.getAccessToken();
   
   if (service.hasAccess()) {
     Logger.log("App has access.");
     var api = "https://api.instamojo.com/v2/user-info";  
     Logger.log(accessToken);
     
     var headers = {
       "Content-Type": "application/x-www-form-urlencoded",
       "Authorization": "Bearer " + getInstamojoService().getAccessToken()
     };
     
     var options = {
       "headers": headers,
       "method" : "GET",
       "muteHttpExceptions": true
     };
     
     var response = UrlFetchApp.fetch(api, options);
     
     var json = JSON.parse(response.getContentText());
     
     Logger.log(response);
     Logger.log(json); 
   }
   else {
     Logger.log("App has no access yet.");
     
     var authorizationUrl = service.getAuthorizationUrl();
     Logger.log("Open the following URL and re-run the script: %s",
         authorizationUrl);
   }
 }
```

**Comment by erickoledadevrel** [comment]
Can you also post the part of your code that is configuring the service? Looking at their API, they seem to have a pretty standard OAuth flow. You can also try printing the result of `service.getToken()` to see if there is something fishy in there.

**Comment by ankurs24** [comment]
`service.getToken()` printed this:
` {{"access_token": "<ACCCESS_TOKEN_HERE>", "expires_in": 36000, "token_type": "Bearer", "scope": "user-info:read", "refresh_token": "<REFRESH_TOKEN_HERE>"}=undefined, granted_time=1.595405296E9}`

Looks like this method is able to return the access token, but not the `getAccessToken()`.

Code that is configuring the service:

```
var CLIENT_ID = <CLIENT_ID_HERE>;
var CLIENT_SECRET = <CLIENT_SECRET_HERE>;

function getInstamojoService() {
  // Create a new service with the given name. The name will be used when
  // persisting the authorized token, so ensure it is unique within the
  // scope of the property store.
  return OAuth2.createService('instamojo')

      // Set the endpoint URLs, which are the same for all Google services.
      .setAuthorizationBaseUrl('https://www.instamojo.com/oauth2/authorize')
      .setTokenUrl('https://www.instamojo.com/oauth2/token/')

      // Set the client ID and secret, from the Google Developers Console.
      .setClientId(CLIENT_ID)
      .setClientSecret(CLIENT_SECRET)

      // Set the name of the callback function in the script referenced
      // above that should be invoked to complete the OAuth flow.
      .setCallbackFunction('authCallback')

      // Set the property store where authorized tokens should be persisted.
      .setPropertyStore(PropertiesService.getUserProperties())

      // Set the scopes to request (space-separated for Google services).
      .setScope('user-info:read')
      .setTokenFormat(OAuth2.TOKEN_FORMAT.FORM_URL_ENCODED)
      .setGrantType('authorization_code')
}

function authCallback(request) {
  var instamojoService = getInstamojoService();
  var isAuthorized = instamojoService.handleCallback(request);
  if (isAuthorized) {
    return HtmlService.createHtmlOutput('Success! You can close this tab.');
  } else {
    return HtmlService.createHtmlOutput('Denied. You can close this tab');
  }
}
```

**Comment by erickoledadevrel** [comment]
The structure of that token doesn't seem correct. It should be a flat list of key-value pairs, but instead most of the token is in a sub-object that is a key in the outer object. The token parsing happens here:

https://github.com/gsuitedevs/apps-script-oauth2/blob/master/src/Service.js#L552

You could try using a local copy of the library and then adding a logging statement to that method to see what the raw response from the server looks like. I'd try to reproduce the error myself, but that API doesn't allow me to sign up.

**Comment by Ettun** [comment]
I experienced this exact same situation, and found the issue was misconfiguration. service.getToken() returned the same malformed object until I switched from `TOKEN_FORMAT.FORM_URL_ENCODED` to `TOKEN_FORMAT.JSON`.

**Comment by erickoledadevrel** [comment]
Of course, thanks for pointing that out. It looks like the API in question does use JSON responses, as per [their docs](https://docs.instamojo.com/v2/docs/authentication-flow). If you remove the line `.setTokenFormat(OAuth2.TOKEN_FORMAT.FORM_URL_ENCODED)` it will revert to JSON which is [the default](https://github.com/gsuitedevs/apps-script-oauth2/blob/master/src/Service.js#L34).
